name: Workflow 1

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Generate HTML file
      run: echo "<html><body>This is an HTML artifact</body></html>" > artifact.html

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: my-html-artifact
        path: artifact.html

    - name: Trigger Workflow2 in Repo-2
      uses: peter-evans/repository-dispatch@v1
      with:
        token: ${{ secrets.ADMIN_TOKEN }}
        repository: repository2-owner/repository2-name
        event-type: trigger-workflow2
        client-payload: |
          {
            "artifact_url": "${{ steps.upload.outputs.artifact_url }}"
          }
