name: Workflow 1

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run script1.sh
      run: |
        chmod +x script1.sh
        ./script1.sh  
