name: Workflow 2

on:
  repository_dispatch:
    types:
      - trigger-workflow2

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Print Message from Workflow 2
      run: echo "Workflow 2 is triggered!"

