name: Workflow 1

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run script1.sh
      env:
        owner-name: ShriniLearns
        repo-name: Repo-1
        REPO_ACCESS_TOKEN: ${{ secrets.ADMIN_TOKEN }}
      run: |
        chmod +x ./Scripts/Script1.sh
        ./Scripts/Script1.sh  "$owner-name" "$repo-name" "${{ env.REPO_ACCESS_TOKEN }}"
      shell: bash
